# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Automação Varejo'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
- name: BRAND_URL
  value: 'https://vertex21.com.br/automacao-varejo'
- name: WIDGET_BRAND_URL
  value: 'https://vertex21.com.br/automacao-varejo'
- name: BRAND_NAME
  value: 'Automação Varejo'
- name: TERMS_URL
  value: 'https://vertex21.com.br/automacao-varejo/terms-of-service'
- name: PRIVACY_URL
  value: 'https://vertex21.com.br/automacao-varejo/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
